<a href="https://colab.research.google.com/github/Phenaoj/Entregables-BIT-PaulaHenao/blob/main/Entregable_2_Completo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#CARGA DEL LA BASE DE DATOS Y LIBRERÍAS
import pandas as pd
import numpy as np
from google.colab import files
uploaded =files.upload()

Saving animal_data_dirty1.csv to animal_data_dirty1 (1).csv

In [32]:
# 1. DIAGNÓSTICO INICIAL
df = pd.read_csv("animal_data_dirty1 (1).csv", sep=";")

# ¿Cuántas filas y columnas tiene el Data Frame?
df.shape

(1011, 11)

In [33]:
#¿Cuáles son las columnas y que tipo de datos tiene cada una?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1011 entries, 0 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       991 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         984 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  1011 non-null   object
 10  Data compiled by  1011 non-null   object
dtypes: float64(5), object(6)
memory usage: 87.0+ KB

In [34]:
#¿Cuántos valores faltantes existen por columna?
df.isnull().sum()

Animal type           20
Country               12
Weight kg             27
Body Length cm        27
Gender                19
Animal code         1011
Latitude              98
Longitude             98
Animal name          959
Observation date       0
Data compiled by       0
dtype: int64

In [36]:
#¿Cuántos registros duplicados existen?
df.duplicated().sum()

np.int64(167)

In [37]:
#Detección de valores sospechosos e incosistentes
for columna in df.select_dtypes(include="object").columns:
    print(f"\n--- {columna} ---")
    print(df[columna].value_counts(dropna=False))

#Problemas identificados: las columnas como Animal type, Country, Gender, Animal Name contienen valores vacios los cuales se deben analizar si son datos relevantes para tener en cuenta o solo harían ruido en el análisis,
#en la columna Animal type se encuentra una misma especie escrita de dos maneras diferentes,
#en la columna Country contamos con los nombres completos pero también con las abreviaciones.

--- Animal type ---
Animal type
red squirrel       543
hedgehog           274
lynx                61
European bison      49
red squirrell       22
NaN                 20
red squirel         14
lynx?               10
European bison™      6
European buster      4
European bisson      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

--- Country ---
Country
Poland            291
Germany           176
Slovakia          151
Hungary           146
Czech Republic    103
Austria            74
PL                 15
NaN                12
HU                 11
Hungry             10
CZ                  5
DE                  5
Czech               4
Australia           4
CC                  4
Name: count, dtype: int64

--- Gender ---
Gender
male              499
female            488
NaN                19
not determined      5
Name: count, dtype: int64

--- Animal name ---
Animal name
NaN           959
Bob Bobson     18
Basia          10
Lola            9
Lolek           4
Zuzia           4
Puchatek        2
Sissi           2
Szefu           1
Klucha          1
Bibi            1
Name: count, dtype: int64

--- Observation date ---
Observation date
01.03.2024    61
02.03.2024    47
06.04.2024    45
04.03.2024    43
02.04.2024    41
              ..
07.06.2024     1
03.14.2024     1
03.13.2024     1
03.11.2024     1
8 May 2024     1
Name: count, Length: 114, dtype: int64

--- Data compiled by ---
Data compiled by
Anne Anthony     473
Bob Bobson       259
John Johnson     249
James Johnson     30
Name: count, dtype: int64

In [38]:
# 2. LIMPIEZA DE DATOS
df.head(6)

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.0,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.0,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony
5,European bisson,Poland,900.0,295.0,male,NaN,52.834759,23.817201,NaN,01.03.2024,Anne Anthony

In [39]:
# Identificar las columnas con valores faltantes y aplica una estrategia de tratamiento adecuada.
df[df["Animal type"].isna()]

# Se puede identificar que una gran mayoría de los registros que tienen valores faltantes en el Animal Type, no aportan información relevante ya que casi todas las columnas están vacías; por consiguiente se puede descartar dichos valores.

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.03.2024,James Johnson
164,NaN,Austria,0.263,22.0,male,NaN,NaN,NaN,NaN,05.03.2024,Bob Bobson
563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.04.2024,James Johnson
626,NaN,Austria,0.319,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
627,NaN,Austria,0.292,19.0,female,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
628,NaN,Austria,0.319,19.0,female,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
629,NaN,Austria,0.298,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
630,NaN,Austria,0.255,22.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
631,NaN,Austria,0.300,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
632,NaN,Austria,0.252,21.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.05.2024,James Johnson
934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.06.2024,James Johnson
956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.07.2024,James Johnson
963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.08.2024,James Johnson
968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.13.2024,James Johnson
969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.14.2024,James Johnson
970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson
971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson

In [40]:
df = df.dropna(subset=["Animal type"])

# Detectar y elimina los registros duplicados cuando corresponda.
# Se va a eliminar aquellas filas que sean completamente iguales
df = df.drop_duplicates()

In [41]:
#Corrección de la columna Animal Type
#Para el caso de Ledgehod, Wedgehod y Hedgehog, se busca en internet y solo el úlitmo nombre arroja un resultado de especie de animales, por ende se estandarizará a dicha especie.
#Caso análogo con el European bison.
df["Animal type"] = df["Animal type"].replace({
    "red squirrell": "red squirrel",
    "red squirel": "red squirrel",
    "ledgehod": "hedgehog",
    "wedgehod": "hedgehog",
    "European bisson": "European bison",
    "European buster": "European bison",
    "European bison™": "European bison",
    "lynx?": "lynx"})

#Corrección de la columna Country
# Estándarizar las abreviaciones del país a su nombre
df["Country"] = df["Country"].replace({
    "PL": "Poland",
    "DE": "Germany",
    "HU": "Hungary",
    "Hungry": "Hungary",
    "CZ": "Czech Republic",
    "Czech": "Czech Republic"})

In [49]:
# Estandarización del formato para la columan Observation Date, teniendo en cuenta que tiene formatos mixtos. Se valida al final que si esté en el formato correcto y no haya valores nulos.
df["Observation date"] = pd.to_datetime(
    df["Observation date"],
    format="mixed",
    dayfirst=True)
print(df["Observation date"].dtype)
df["Observation date"].isna().sum()

datetime64[ns]

np.int64(0)

In [56]:
# Ahora se revisa la calidad de datos para las columnas Weight kg y Body Length cm
df[["Weight kg", "Body Length cm"]].describe()

#Aparece que hay valores negativos, los cuales no tienen sentido para hablar de peso y longitud de un animal

         Weight kg  Body Length cm
count   816.000000      816.000000
mean     47.867358       42.933824
std     170.513704       63.682383
min      -0.252000      -19.000000
25%       0.298000       19.000000
50%       0.400000       21.000000
75%       1.000000       23.000000
max    1100.000000      350.000000

In [59]:
#Ubicaremos los datos negativos para el peso
df[df["Weight kg"] < 0]

#Vemos que el registro tiene más información de valor, por lo que no justifica eliminarlo, sino modificarlos, se hará en el punto de Numpy

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
457,red squirrel,Hungary,-0.251,20.0,female,NaN,47.508618,18.944915,NaN,2024-03-26,Anne Anthony
503,red squirrel,Hungary,-0.250,19.0,female,NaN,47.509538,18.945968,NaN,2024-03-31,Anne Anthony
663,red squirrel,Slovakia,-0.252,21.0,male,NaN,49.057599,22.422203,NaN,2024-04-08,John Johnson

In [62]:
#Comprobación de la limpieza
df.shape

#Pasamos de 1011 filas a 825

(825, 11)

In [63]:
df.duplicated().sum()

#Ya no tenemos valores duplicados

np.int64(0)

In [64]:
for columna in ["Animal type", "Country"]:
    print(f"\n--- {columna} ---")
    print(df[columna].value_counts(dropna=False))

#Ya en Animal Type no existe registros vacios, además se simplificaron la cantidad de animales, para Country ya no se encuentra las abreviaciones, solo los nombres completos de los paises.

--- Animal type ---
Animal type
red squirrel      413
hedgehog          278
lynx               71
European bison     63
Name: count, dtype: int64

--- Country ---
Country
Poland            192
Germany           178
Slovakia          151
Hungary           118
Czech Republic    112
Austria            66
Australia           4
CC                  4
Name: count, dtype: int64

In [72]:
# 3. USO DE NUMPY
# Calculamos la mediana de Red Squirrel tomando sus valores mayores que 0
mediana_red_squirrel = np.median(
    df.loc[(df["Animal type"] == "red squirrel") & (df["Weight kg"] >= 0),"Weight kg"])

mediana_red_squirrel
print(mediana_red_squirrel)

# Vamos a reemplazar los valores negativos por la mediana para poder terminar de limpiar los registros
df["Weight kg"] = np.where((df["Animal type"] == "red squirrel") & (df["Weight kg"] < 0), mediana_red_squirrel, df["Weight kg"])

#Cómo se mencionó anteriormente, se identicó un valor erroneo en los registros para peso, sin embargo, al ser registros válidos se optó por reemplazar dichos valores negativos con la mediana específicamente de dicha especie.

0.298

In [74]:
# 4. ANÁLISIS CON GROUPBY
#¿Cuál es el número de observaciones por tipo de animal?
observations_animal = (df.groupby("Animal type").size().sort_values(ascending=False))

observations_animal

Animal type
red squirrel      413
hedgehog          278
lynx               71
European bison     63
dtype: int64

In [75]:
#¿Cuál es el promedio de una variable numérica según el tipo de animal?
average_weight_animal = (df.groupby("Animal type")["Weight kg"].mean().sort_values(ascending=False))

average_weight_animal

Animal type
European bison    588.396825
lynx               23.267606
hedgehog            0.797455
red squirrel        0.297570
Name: Weight kg, dtype: float64

In [76]:
#¿Cuál es el peso promedio de cada tipo de animal en cada país?
average_weight_country_animal = (
    df.groupby(["Country", "Animal type"])["Weight kg"].mean().sort_index())

average_weight_country_animal

Country         Animal type
Australia       hedgehog            0.700000
                red squirrel        0.288000
Austria         hedgehog            0.788000
                lynx               22.200000
                red squirrel        0.301694
CC              European bison    634.000000
Czech Republic  European bison    490.083333
                hedgehog            0.782143
                lynx               21.250000
                red squirrel        0.298833
Germany         hedgehog            0.772581
                red squirrel        0.286931
Hungary         hedgehog            0.839623
                lynx               21.461538
                red squirrel        0.291812
Poland          European bison    641.526316
                hedgehog            0.809524
                lynx               27.842105
                red squirrel        0.309780
Slovakia        European bison    474.888889
                hedgehog            0.803571
                lynx               21.653846
                red squirrel        0.297650
Name: Weight kg, dtype: float64

In [81]:
#¿Cuántos registros de cada tipo de animal hay en cada país?
observations_animal_country = (
    df.groupby(["Country", "Animal type"]).size().reset_index(name="Observations")
    .sort_values(["Country", "Observations"],ascending=[True, False]))

observations_animal_country

           Country     Animal type  Observations
0        Australia        hedgehog             2
1        Australia    red squirrel             2
4          Austria    red squirrel            36
2          Austria        hedgehog            25
3          Austria            lynx             5
5               CC  European bison             4
7   Czech Republic        hedgehog            56
9   Czech Republic    red squirrel            36
6   Czech Republic  European bison            12
8   Czech Republic            lynx             8
11         Germany    red squirrel           116
10         Germany        hedgehog            62
12         Hungary        hedgehog            56
14         Hungary    red squirrel            49
13         Hungary            lynx            13
18          Poland    red squirrel           114
15          Poland  European bison            38
16          Poland        hedgehog            21
17          Poland            lynx            19
22        Slovakia    red squirrel            60
20        Slovakia        hedgehog            56
21        Slovakia            lynx            26
19        Slovakia  European bison             9

In [80]:
#¿Cuántas observaciones de cada tipo de animal fueron registradas por cada persona que compiló los datos?
observations_compiler_animal = (
    df.groupby(["Data compiled by", "Animal type"]).size()
    .reset_index(name="Observations")
    .sort_values(["Data compiled by", "Observations"],ascending=[True, False]))

observations_compiler_animal

   Data compiled by     Animal type  Observations
3      Anne Anthony    red squirrel           163
1      Anne Anthony        hedgehog            77
0      Anne Anthony  European bison            38
2      Anne Anthony            lynx            32
6        Bob Bobson    red squirrel           154
4        Bob Bobson        hedgehog            89
5        Bob Bobson            lynx             5
9     James Johnson    red squirrel            12
7     James Johnson        hedgehog             3
8     James Johnson            lynx             3
11     John Johnson        hedgehog           109
13     John Johnson    red squirrel            84
12     John Johnson            lynx            31
10     John Johnson  European bison            25

In [82]:
#¿Cuántos registros tiene cada persona que compiló los datos en cada país?
observations_compiler_country = (
    df.groupby(["Country", "Data compiled by"]).size().reset_index(name="Observations")
    .sort_values(["Country", "Observations"],ascending=[True, False]))

observations_compiler_country

          Country Data compiled by  Observations
0       Australia       Bob Bobson             4
1         Austria       Bob Bobson            66
2              CC     John Johnson             4
3  Czech Republic     John Johnson           112
4         Germany       Bob Bobson           178
5         Hungary     Anne Anthony           118
6          Poland     Anne Anthony           192
8        Slovakia     John Johnson           133
7        Slovakia    James Johnson            18

In [ ]:
# 5. INTERPRETACIÓN DE LOS RESULTADOS
# Conckusión 1:Más del 80 % de los registros obtenidos se concentran en dos especies: Red Squirell (413 registros) y Hedgehog (278 registros). Adicionalmente, el European Bison, es el animal con menos registros obtenidos
# Conclusión 2:Para el Eurpean Bison, se evidencia que existe una variación significativa en el peso promedio por país siendo de 641.53 kg en Poland, frente a 474.89 kg en Slovakia y 490.08 kg en Czech Republic, sin embargo, no son equivalentes la cantidad de registros que se tuvo en cada país ya que se dieron 38, 9 y 12 registros respectivamente, por consiguiente se debe tener en cuenta dicha cantidad a la hora de hacer conclusiones.
# Conclusión 3:La cantidad de registros también presenta una concentración según la persona que compiló los datos y el país. Anne Anthony realizó 192 registros en Poland y 118 en Hungary, mientras que Bob Bobson realizó 178 en Germany y 66 en Austria. John Johnson realizó 112 registros en Czech Republic y 133 en Slovakia, donde además James Johnson realizó otros 18. Esto muestra que la distribución de las observaciones entre países no es uniforme y que algunos recopiladores concentran una parte importante de los registros de determinados países.
# Conclusión 4:La composición de los registros por animal ayuda a contextualizar las diferencias de peso observadas entre países. Por ejemplo, Poland cuenta con 38 registros de European bison, cuyo peso promedio es de 641.53 kg, mientras que Slovakia tiene solo 9 registros de esta especie, con un promedio de 474.89 kg. Al mismo tiempo, Slovakia concentra más registros de animales de menor peso, como red squirrel (60) y hedgehog (56). Esto muestra que las diferencias en los promedios de peso entre países deben analizarse teniendo en cuenta qué tipos de animales y en qué cantidad están representados en cada país.